cta/agendamento/urls.py
from django.conf.urls import url

from cta.agendamento.views import form_agendamento, apagar_agendamento, editar_agendamento


urlpatterns = [
    url(r'^formulario-agendamento/$', form_agendamento, name='agendamento'),
    url(r'^deletar-agendamento/(?P<id>\d+)/$', apagar_agendamento, name='apagaragendamento'),
    url(r'^editar-agendamento/(?P<id>\d+)/$', editar_agendamento, name='editaragendamento'),    
]

cta/atendimento/urls.py
from django.conf.urls import url

from cta.atendimento.views import form_atendimento, apagar_atendimento, editar_atendimento


urlpatterns = [
    url(r'^formulario-atendimento/$', form_atendimento, name='atendimento'),
    url(r'^deletar-atendimento/(?P<id>\d+)/$', apagar_atendimento, name='apagaratendimento'),
    url(r'^editar-atendimento/(?P<id>\d+)/$', editar_atendimento, name='editaratendimento'),    
]

cta/core/urls.py
from django.conf.urls import url

from cta.core.views import home, cadastro_usuario, sucesso_usuario,\
user_login, user_logout, consulta_agendamento, consulta_atendimento,\
consulta_fornecedor, consulta_representante, consulta_objetivovisita, email_contato

urlpatterns = [
    url(r'^$', user_login, name='userlogin'),
    url(r'^home/$', home, name='home'),
    url(r'^logout/$', user_logout, name='userlogout'),    
    url(r'^cadastro-usuario/$', cadastro_usuario, name='cadastrousuario'),
    url(r'^sucesso-usuario/$', sucesso_usuario, name='usuariosucesso'),
    url(r'^consulta-agendamento/$', consulta_agendamento, name='consultaagendamento'),
    url(r'^consulta-atendimento/$', consulta_atendimento, name='consultaatendimento'),
    url(r'^consulta-fornecedor/$', consulta_fornecedor, name='consultafornecedor'),
    url(r'^consulta-representante/$', consulta_representante, name='consultarepresentante'),
    url(r'^consulta-objetivovisita/$', consulta_objetivovisita, name='consultaobjetivovisita'),
    url(r'^email-contato/$', email_contato, name='contato'),
]

cta/fornecedor/urls.py
from django.conf.urls import url

from cta.fornecedor.views import cadastro_fornecedor, apagar_fornecedor, editar_fornecedor


urlpatterns = [
    url(r'^cadastro-fornecedor/$', cadastro_fornecedor, name='fornecedor'),
    url(r'^deletar-fornecedor/(?P<id>\d+)/$', apagar_fornecedor, name='apagarfornecedor'),
    url(r'^editar-fornecedor/(?P<id>\d+)/$', editar_fornecedor, name='editarfornecedor'),
]

cta/representante/urls.py
from django.conf.urls import url

from cta.representante.views import cadastro_representante, apagar_representante, editar_representante


urlpatterns = [
    url(r'^cadastro-representante/$', cadastro_representante, name='representante'),
    url(r'^deletar-representante/(?P<id>\d+)/$', apagar_representante, name='apagarrepresentante'),
    url(r'^editar-representante/(?P<id>\d+)/$', editar_representante, name='editarrepresentante'),
]

cta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cta.core import urls as core_urls
from cta.agendamento import urls as agendamento_urls
from cta.atendimento import urls as atendimento_urls
from cta.fornecedor import urls as fornecedor_urls
from cta.objetivovisita import urls as objetivovisita_urls
from cta.representante import urls as representante_urls

from django.conf import settings

urlpatterns = [
	url(r'', include(core_urls, namespace='core')),
	url(r'', include(agendamento_urls, namespace='agendamento')),
	url(r'', include(atendimento_urls, namespace='atendimento')),
	url(r'', include(fornecedor_urls, namespace='fornecedor')),
	url(r'', include(objetivovisita_urls, namespace='objetivovisita')),
    url(r'', include(representante_urls, namespace='representante')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),    
]

cta/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	telefone = models.CharField(u'Celular', max_length=14, help_text='(99)99999-9999')
	foto = models.ImageField(upload_to="media/profile", blank=True)
	data_cadastro = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.first_name

cta/core/forms.py
from django import forms
from django.contrib.auth.models import User

from cta.core.models import UserProfile

class UserForm(forms.ModelForm):
	#first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		exclude = ('user', 'data_cadastro')

cta/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError

from .forms import UserForm, UserProfileForm
from cta.agendamento.models import Agendamento
from cta.atendimento.models import Atendimento

from cta.fornecedor.models import Fornecedor
from cta.representante.models import Representante
from cta.objetivovisita.models import Objetivovisita

# Create your views here.

from django.contrib.auth.decorators import login_required

def home(request):
	return render(request, 'base.html')

def cadastro_usuario(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user

			if 'foto' in request.FILES:
				profile.foto = request.FILES['foto']

			profile.save()
			return redirect('core:cadastrousuario') #core:usuariosucesso
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'core/cadastro_usuario.html',\
		{'user_form': user_form, 'profile_form': profile_form})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return redirect('core:home') #HttpResponse("Login feito com sucesso.")
			else:				
				mensg = "Sua conta esta desativada."
				return render(request,'core/form_login.html', {'mensg': mensg}) #HttpResponse("Sua conta esta desativada.")
		else:
			mensg = "Usuario ou senha invalido."
			return render(request,'core/form_login.html', {'mensg': mensg}) #HttpResponse("Usuario ou senha invalido.")
	return render(request, 'core/form_login.html')

def sucesso_usuario(request):
	return render(request, 'base.html') #core/sucesso_usuario.html

def user_logout(request):
    logout(request)
    return redirect('core:userlogin')

@login_required(login_url = 'core:userlogin')
def consulta_agendamento(request):
	agendamentos = Agendamento.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_agendamento.html', {'agendamentos': agendamentos})

@login_required(login_url = 'core:userlogin')
def consulta_atendimento(request):
	atendimentos = Atendimento.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_atendimento.html', {'atendimentos': atendimentos})

@login_required(login_url = 'core:userlogin')
def consulta_fornecedor(request):
	fornecedores = Fornecedor.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_fornecedor.html', {'fornecedores': fornecedores})

@login_required(login_url = 'core:userlogin')
def consulta_representante(request):
	representantes = Representante.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_representante.html', {'representantes': representantes})

@login_required(login_url = 'core:userlogin')
def consulta_objetivovisita(request):
	objetivovisitas = Objetivovisita.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_objetivovisita.html', {'objetivovisitas': objetivovisitas})

def email_contato(request):
	if request.method == 'POST':
		subject = request.POST.get('subject')
		message = request.POST.get('inputmessage')
		from_email = "flavioleny@gmail.com"
		for_email  = request.POST.get('inputemail')

		if subject and message and for_email:
			send_mail(subject, message, from_email, [for_email], fail_silently=True)

			mensg = "E-mail enviado com Sucesso..."
			return render(request,'core/contato.html', {'mensg': mensg})
		else:
			mensg = "Todos os campos são Obrigatorios."
			return render(request,'core/contato.html', {'mensg': mensg})
	else:
		return render(request, 'core/contato.html')

cta/core/templates/core/cadastro_usuario.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Cadastro de usuario | {{ block.super }}
{% endblock titulo %}

{% block row %}

<div class="col-md-6">
	<div class="well bs-component">
		{% if menssagem %}
			{{ menssagem }}
		{% endif %}
		<form class="form-horizontal" action="" method="post" accept-charset="utf-8" enctype="multipart/data-form">
		  <fieldset>
	      	<legend>Cadastro de Usuário</legend>
			{% csrf_token %}
			<div class="form-group">
				<label for="id_first_name" class="col-lg-2 control-label">Nome</label>
				<div class="col-lg-10">
					{{ user_form.first_name|add_class:"form-control"|attr:"required:required" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_last_name" class="col-lg-2 control-label">Sobrenome</label>
				<div class="col-lg-10">
					{{ user_form.last_name|add_class:"form-control"|attr:"required:required" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_email" class="col-lg-2 control-label">Email</label>
				<div class="col-lg-10">
					{{ user_form.email|add_class:"form-control"|attr:"required:required" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_username" class="col-lg-2 control-label">Usuário</label>
				<div class="col-lg-10">
					{{ user_form.username|add_class:"form-control"|attr:"required:required" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_password" class="col-lg-2 control-label">Senha</label>
				<div class="col-lg-10">
					{{ user_form.password|add_class:"form-control"|attr:"type:password" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_telefone" class="col-lg-2 control-label">Telefone</label>
				<div class="col-lg-10">
					{{ profile_form.telefone|add_class:"form-control"|attr:"required:required" }}
				</div>
			</div>
			<div class="form-group">
				<label for="exampleInputFile" class="col-lg-2 control-label">Foto</label>
				<div class="col-lg-10">
					<!--{{ profile_form.foto|add_class:"form-control" }} -->
					<input id="exampleInputFile" type="file">
				</div>
			</div>
			<button type="submit" class="btn btn-primary">Salvar</button>
			</fieldset>
		</form>
	</div>
</div>
{% endblock row %}

cta/core/templates/core/consulta_agendamento.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Consulta de Agendamento | {{ block.super }}
{% endblock titulo %}

{% block row %}
<div class="well bs-component">
	Consulta de Agendamento
</div>

<div class="well bs-component">
	<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Atendente</th>
                <th>Data Agendamento</th>
                <th>Data Atendimento</th>
                <th>Representante</th>
                <th>Objetivo Atendimento</th>
                <th>Status</th>
                <th>Observacao</th>
                <th></th>
                <th></th>                
            </tr>
        </thead>
 
        <tbody>

			{% for c in agendamentos %}
				<tr class="active">
					<td>{{ c.id }}</td>
					<td>{{ c.atendente }}</td>
					<td>{{ c.dataagendamento|date:"d/m/Y" }}</td>
					<td>{{ c.dataatendimento|date:"d/m/Y - H:i:s" }}</td>
					<td>{{ c.representante }}</td>
					<td>{{ c.objetivoatendimento }}</td>
					<td>{{ c.status }}</td>
					<td>{{ c.observacao }}</td>
                    <td><a href="{% url 'agendamento:editaragendamento' c.id %}"> <i class="glyphicon glyphicon-edit" ></i> </a></td>
                    <td><a href="{% url 'agendamento:apagaragendamento' c.id %}"> <i class="glyphicon glyphicon-trash" ></i> </a></td>                    
				</tr>
			{% endfor %}

        </tbody>
    </table>
</div>
{% endblock row %}

cta/core/templates/core/consulta_atendimento.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Consulta de Atendimento | {{ block.super }}
{% endblock titulo %}

{% block row %}
<div class="well bs-component">
	Consulta de Atendimento
</div>

<div class="well bs-component">
	<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Atendente</th>
                <th>Data Atendimento</th>
                <th>horainicial</th>
                <th>horafinal</th>
                <th>Objetivo Atendimento</th>
                <th>Status</th>
                <th>Conteudo Atendimento</th>
                <th>Observacao</th>
                <th></th>
                <th></th>                
            </tr>
        </thead>
 
        <tbody>

			{% for c in atendimentos %}
				<tr class="active">
					<td>{{ c.id }}</td>
					<td>{{ c.atendente }}</td>
                    <td>{{ c.dataatendimento|date:"d/m/Y" }}</td>
                    <td>{{ c.horainicial|date:"H:i:s" }}</td>
					<td>{{ c.horafinal|date:"H:i:s" }}</td>
					<td>{{ c.objetivoatendimento }}</td>
                    <td>{{ c.status }}</td>
					<td>{{ c.conteudoatendimento }}</td>
					<td>{{ c.observacao }}</td>
                    <td><a href="{% url 'atendimento:editaratendimento' c.id %}"> <i class="glyphicon glyphicon-edit" ></i> </a></td>
                    <td><a href="{% url 'atendimento:apagaratendimento' c.id %}"> <i class="glyphicon glyphicon-trash" ></i> </a></td>                    
				</tr>
			{% endfor %}

        </tbody>
    </table>
</div>
{% endblock row %}

cta/core/templates/core/consulta_fornecedor.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Consulta de Fornecedor | {{ block.super }}
{% endblock titulo %}

{% block row %}
<div class="well bs-component">
	Consulta de Fornecedor
</div>

<div class="well bs-component">
	<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Razao Social</th>
                <th>Cgccpf</th>
                <th>Endereço</th>
                <th>Cep</th>
                <th>Bairro</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Fone1</th>
                <th>E-mail</th>
                <th></th>
                <th></th>                
            </tr>
        </thead>
 
        <tbody>

			{% for c in fornecedores %}
				<tr class="active">
                    <td>{{ c.id }}</td>
                    <td>{{ c.razaosocial }}</td>
                    <td>{{ c.cgccpf }}</td>
                    <td>{{ c.endereco }}</td>
                    <td>{{ c.cep }}</td>
                    <td>{{ c.bairro }}</td>
                    <td>{{ c.cidade }}</td>
                    <td>{{ c.estado }}</td>
                    <td>{{ c.fone1 }}</td>
                    <td>{{ c.email }}</td>
                    <td><a href="{% url 'fornecedor:editarfornecedor' c.id %}"> <i class="glyphicon glyphicon-edit" ></i> </a></td>
                    <td><a href="{% url 'fornecedor:apagarfornecedor' c.id %}"> <i class="glyphicon glyphicon-trash" ></i> </a></td>                    
				</tr>
			{% endfor %}

        </tbody>
    </table>
</div>
{% endblock row %}

cta/core/templates/core/consulta_objetivovisita.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Consulta de Objetivo Visita | {{ block.super }}
{% endblock titulo %}

{% block row %}
<div class="col-md-6">
<div class="well bs-component">
	Consulta de Objetivo Visita
</div>

<div class="well bs-component">
	<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Título</th>
                <th></th>
                <th></th>                
            </tr>
        </thead>
 
        <tbody>

			{% for c in objetivovisitas %}
				<tr class="active">
                    <td>{{ c.id }}</td>
                    <td>{{ c.titulo }}</td>
                    <td><a href="{% url 'objetivovisita:editarobjetivovisita' c.id %}"> <i class="glyphicon glyphicon-edit" ></i> </a></td>
                    <td><a href="{% url 'objetivovisita:apagarobjetivovisita' c.id %}"> <i class="glyphicon glyphicon-trash" ></i> </a></td>      
				</tr>
			{% endfor %}

        </tbody>
    </table>
</div>
</div>
{% endblock row %}

cta/core/templates/core/consulta_representante.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Consulta de Representante | {{ block.super }}
{% endblock titulo %}

{% block row %}

<div class="col-md-6">
<div class="well bs-component">Consulta de Representante</div>

<div class="well bs-component">
	<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Nome Representante</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
 
        <tbody>

			{% for c in representantes %}
				<tr class="active">
                    <td>{{ c.id }}</td>
                    <td>{{ c.nomerepresentante }}</td>
                    <td><a href="{% url 'representante:editarrepresentante' c.id %}"> <i class="glyphicon glyphicon-edit" ></i> </a></td>
                    <td><a href="{% url 'representante:apagarrepresentante' c.id %}"> <i class="glyphicon glyphicon-trash" ></i> </a></td>
				</tr>
			{% endfor %}

        </tbody>
    </table>
</div>
</div>
{% endblock row %}

cta/core/templates/core/contato.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
	Contato | {{ block.super }}
{% endblock titulo %}

{% block row %}

<div class="col-md-8">
	<div class="well bs-component">
  		{% if mensg %}
  			{{ mensg }}
  		{% endif %}

		<form class="form-horizontal" method="post" action="" enctype="multipart/data-form">
	      {% csrf_token %}
		  
		  <fieldset>
	      	<legend>Formulário de Contato
	      	</legend>

			<div class="form-group">
				<label for="id_nome" class="col-lg-2 control-label">Nome:</label>
				<div class="col-lg-10">				
					<input class="form-control" id="realname" placeholder="Nome" type="text" required name="realname">
				</div>
			</div>
			<div class="form-group">
				<label for="id_email" class="col-lg-2 control-label">E-mail:</label>
				<div class="col-lg-10">				
					<input class="form-control" id="inputemail" placeholder="E-mail" type="text" required name="inputemail">
				</div>
			</div>
			<div class="form-group">
				<label for="id_assunto" class="col-lg-2 control-label">Assunto:</label>
				<div class="col-lg-10">
					<input class="form-control" id="subject" placeholder="Assunto" type="text" required name="subject">
				</div>
			</div>
			<div class="form-group">
				<label for="id_mensagem" class="col-lg-2 control-label">Mensagem:</label>
				<div class="col-lg-10">
					<textarea rows=8 cols=50 class="form-control" id="inputmessage" type="text" required name="inputmessage"> </textarea>
				</div>
			</div>
			<input class="btn btn-primary" type="submit" value="Envie sua mensagem" name="submit" >
			<input class="btn btn-primary" type="reset" value="Limpar" name="reset">
			</form>
			
		</fieldset>
	</div>
	<i class="glyphicon glyphicon-user"></i> - Flávio Santos
</div>

{% endblock row %}

cta/core/templates/core/form_login.html
{% extends "base_login.html" %}

{% load staticfiles %}

{% load widget_tweaks %}

{% block titulo %}
	Login | {{ block.super }}

{% endblock titulo %}

{% block row %}
	<div id="wrapper">
		<img src="{% static "images/Black_and_white_218x75.png" %}" alt=""> 
		<div>{{ mensg }}</div>
		<div id="wrappertop"></div>

		<div id="wrappermiddle">
			
			<h2>Login</h2>

			<form action="" method="post" accept-charset="utf-8" enctype="multipart/data-form">
			{% csrf_token %}

				<div id="username_input">

					<div id="username_inputleft"></div>
					<div id="username_inputmiddle">
						<input type="text" name="username" id="url" value="Nome do Usuário" onclick="this.value = ''">
						<img id="url_user" src="{% static "images/mailicon.png" %}" alt="">
					</div>
					<div id="username_inputright"></div>

				</div>

				<div id="password_input">
					<div id="password_inputleft"></div>
					<div id="password_inputmiddle">
						<input type="password" name="password" id="url" value="Password" onclick="this.value = ''">
						<img id="url_password" src="{% static "images/passicon.png" %}" alt="">
					</div>
					<div id="password_inputright"></div>

				</div>

				<div id="submit">
					<input type="image" src="{% static "images/submit_hover.png" %}" id="submit1" value="Entrar">
					<input type="image" src="{% static "images/submit.png" %}" id="submit2" value="Entrar">
				</div>
			</form>
			<div id="links_left">
				<!-- <a href="#">Forgot your Password?</a> -->
			</div>

			<!-- <div id="links_right"><a href="#">Not a Member Yet?</a></div> -->

		</div>

		<div id="wrapperbottom"></div>
		
		<div id="powered">
		<p>Criado por <a href="">Flávio Santos</a></p>
		</div>
	</div>

{% endblock row %}

cta/core/templates/core/sucesso_usuario.html
{% extends "base.html" %}

{% block titulo %}
Sucesso usuario | {{ block.super }}
{% endblock titulo %}

{% block row %}
<p>Usuario cadastrado com sucesso.</p>
<p>
	Agora voce esta pronto para criar suas campanhas.
</p>
{% endblock row %}