cta/fornecedor/urls.py
from django.conf.urls import url

from cta.fornecedor.views import cadastro_fornecedor, apagar_fornecedor, editar_fornecedor


urlpatterns = [
    url(r'^cadastro-fornecedor/$', cadastro_fornecedor, name='fornecedor'),
    url(r'^deletar-fornecedor/(?P<id>\d+)/$', apagar_fornecedor, name='apagarfornecedor'),
    url(r'^editar-fornecedor/(?P<id>\d+)/$', editar_fornecedor, name='editarfornecedor'),
]

cta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cta.core import urls as core_urls
from cta.agendamento import urls as agendamento_urls
from cta.atendimento import urls as atendimento_urls
from cta.fornecedor import urls as fornecedor_urls
from cta.objetivovisita import urls as objetivovisita_urls
from cta.representante import urls as representante_urls

from django.conf import settings

urlpatterns = [
	url(r'', include(core_urls, namespace='core')),
	url(r'', include(agendamento_urls, namespace='agendamento')),
	url(r'', include(atendimento_urls, namespace='atendimento')),
	url(r'', include(fornecedor_urls, namespace='fornecedor')),
	url(r'', include(objetivovisita_urls, namespace='objetivovisita')),
    url(r'', include(representante_urls, namespace='representante')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),    
]

cta/fornecedor/models.py
from django.db import models

# Create your models here.

class Fornecedor(models.Model):
	#choices_pessoa=(('F','Fisica'),('J','Juridica'))
	#choices_atividade=(('C','Comercial'),('D','Distribuidor'),('I','Industria'))
    id = models.AutoField(primary_key=True)
    atividade = models.CharField(u'Atividade',max_length=1,choices=(('C','Comercial'),('D','Distribuidor'),('I','Industria')))
    prazopagamento = models.CharField(max_length=20)
    tipopessoa = models.CharField(u'Pessoa',max_length=1,choices=(('F','Fisica'),('J','Juridica')))
    representante = models.CharField(max_length=30)
    razaosocial = models.CharField(max_length=50)
    cgccpf = models.CharField(u'Cgccpf', max_length=18, help_text='99.999.999/9999-99')
    endereco = models.CharField(max_length=60)
    complemento = models.CharField(max_length=30)
    cep = models.CharField(u'Cep', max_length=10, help_text='99.999-999')
    bairro = models.CharField(max_length=30)
    cidade =  models.CharField(max_length=30, default='Teresina')
    estado =  models.CharField(max_length=2, default='PI')
    fone1 = models.CharField(u'Celular', max_length=14, help_text='(99)99999-9999')
    fone2 = models.CharField(u'Celular', max_length=14, help_text='(99)99999-9999')
    email = models.CharField(max_length=100)
    datacadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	return self.nome

    class Meta:
        verbose_name='Fornecedor'
        verbose_name_plural='Fornecedor'        

cta/fornecedor/forms.py
from django import forms

from cta.fornecedor.models import Fornecedor

class FornecedorForm(forms.ModelForm):
	class Meta:
		model = Fornecedor
		fields = ('atividade', 'prazopagamento', 'tipopessoa', 'representante', \
			      'razaosocial','cgccpf','endereco','complemento','cep','bairro',\
			      'cidade','estado','fone1','fone2','email')

cta/fornecedor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.core.urlresolvers import reverse

from cta.fornecedor.forms import FornecedorForm
from cta.fornecedor.models import Fornecedor


# Create your views here.

from django.contrib.auth.decorators import login_required

@login_required(login_url = 'core:userlogin')
def cadastro_fornecedor(request):
	newcadastro = 'S'
	if request.method == 'POST':
		fornecedor_form = FornecedorForm(request.POST, request.FILES)
		if fornecedor_form.is_valid():
			fornecedor_form.save()
			fornecedor_form = FornecedorForm()
			return render(request, 'cadastro_fornecedor.html', {'fornecedor_form': fornecedor_form, 'newcadastro': newcadastro})
			#return redirect('/')
	else:
		fornecedor_form = FornecedorForm()

	return render(request, 'cadastro_fornecedor.html', {'fornecedor_form': fornecedor_form, 'newcadastro': newcadastro})

def apagar_fornecedor(request, id):
	fornecedores = Fornecedor.objects.get(id=id).delete()
	return redirect(reverse('core:consultafornecedor'))

def editar_fornecedor(request,id):
	fornecedores = Fornecedor.objects.get(id=id)
	newcadastro = 'N'
	if request.method == 'POST':
		fornecedor_form = FornecedorForm(request.POST, instance=fornecedores)
		if fornecedor_form.is_valid:
			fornecedor_form.save()
			return redirect(reverse('core:consultafornecedor'))
		else:
			print(fornecedor_form.errors)
	else:
		fornecedor_form = FornecedorForm(instance=fornecedores)
	
	return render(request, 'cadastro_fornecedor.html',{'fornecedor_form':fornecedor_form, 'newcadastro': newcadastro})

cta/fornecedor/templates/cadastro_fornecedor.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Cadastro de Fornecedor | {{ block.super }}
{% endblock titulo %}

{% block row %}

<div class="col-md-8">
	<div class="well bs-component">
	{% if menssagem %}
		{{ menssagem }}
	{% endif %}
	<form class="form-horizontal" action="" method="post" accept-charset="utf-8" enctype="multipart/data-form">
		<fieldset>
	    <legend>
	    	{% if newcadastro == 'S' %}
	    		Cadastro de Fornecedor
			{% else %}      		
				Editar Fornecedor
      		{% endif %}	 
		</legend>
		
		{% csrf_token %}
		<div class="form-group">
			<label for="id_atividade" class="col-lg-2 control-label">Atividade</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.atividade|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_prazopagamento" class="col-lg-2 control-label">Prazo Pagamento</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.prazopagamento|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_tipopessoa" class="col-lg-2 control-label">Tipo Pessoa</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.tipopessoa|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_representante" class="col-lg-2 control-label">Representante</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.representante|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_razaosocial" class="col-lg-2 control-label">Razão Social</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.razaosocial|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_cgccpf" class="col-lg-2 control-label">Cgc/Cpf</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.cgccpf|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_endereco" class="col-lg-2 control-label">Endereço</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.endereco|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_complemento" class="col-lg-2 control-label">Complemento</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.complemento|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_cep" class="col-lg-2 control-label">Cep</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.cep|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_bairro" class="col-lg-2 control-label">Bairro</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.bairro|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_cidade" class="col-lg-2 control-label">Cidade</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.cidade|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_estado" class="col-lg-2 control-label">Estado</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.estado|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_fone1" class="col-lg-2 control-label">Fone 1</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.fone1|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_fone2" class="col-lg-2 control-label">Fone 2</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.fone2|add_class:"form-control" }}
			</div>
		</div>
		<div class="form-group">
			<label for="id_email" class="col-lg-2 control-label">Email</label>
			<div class="col-lg-10">			
				{{ fornecedor_form.email|add_class:"form-control" }}
			</div>
		</div>
		<button type="submit" class="btn btn-primary">Salvar</button>
		</fieldset>
	</form>
</div>
{% endblock row %}