cta/agendamento/urls.py
from django.conf.urls import url

from cta.agendamento.views import form_agendamento, apagar_agendamento, editar_agendamento


urlpatterns = [
    url(r'^formulario-agendamento/$', form_agendamento, name='agendamento'),
    url(r'^deletar-agendamento/(?P<id>\d+)/$', apagar_agendamento, name='apagaragendamento'),
    url(r'^editar-agendamento/(?P<id>\d+)/$', editar_agendamento, name='editaragendamento'),    
]

cta/atendimento/urls.py
from django.conf.urls import url

from cta.atendimento.views import form_atendimento, apagar_atendimento, editar_atendimento


urlpatterns = [
    url(r'^formulario-atendimento/$', form_atendimento, name='atendimento'),
    url(r'^deletar-atendimento/(?P<id>\d+)/$', apagar_atendimento, name='apagaratendimento'),
    url(r'^editar-atendimento/(?P<id>\d+)/$', editar_atendimento, name='editaratendimento'),    
]

cta/core/urls.py
from django.conf.urls import url

from cta.core.views import home, cadastro_usuario, sucesso_usuario,\
user_login, user_logout, consulta_agendamento, consulta_atendimento,\
consulta_fornecedor, consulta_representante, consulta_objetivovisita, email_contato

urlpatterns = [
    url(r'^$', user_login, name='userlogin'),
    url(r'^home/$', home, name='home'),
    url(r'^logout/$', user_logout, name='userlogout'),    
    url(r'^cadastro-usuario/$', cadastro_usuario, name='cadastrousuario'),
    url(r'^sucesso-usuario/$', sucesso_usuario, name='usuariosucesso'),
    url(r'^consulta-agendamento/$', consulta_agendamento, name='consultaagendamento'),
    url(r'^consulta-atendimento/$', consulta_atendimento, name='consultaatendimento'),
    url(r'^consulta-fornecedor/$', consulta_fornecedor, name='consultafornecedor'),
    url(r'^consulta-representante/$', consulta_representante, name='consultarepresentante'),
    url(r'^consulta-objetivovisita/$', consulta_objetivovisita, name='consultaobjetivovisita'),
    url(r'^email-contato/$', email_contato, name='contato'),
]

cta/fornecedor/urls.py
from django.conf.urls import url

from cta.fornecedor.views import cadastro_fornecedor, apagar_fornecedor, editar_fornecedor


urlpatterns = [
    url(r'^cadastro-fornecedor/$', cadastro_fornecedor, name='fornecedor'),
    url(r'^deletar-fornecedor/(?P<id>\d+)/$', apagar_fornecedor, name='apagarfornecedor'),
    url(r'^editar-fornecedor/(?P<id>\d+)/$', editar_fornecedor, name='editarfornecedor'),
]

cta/representante/urls.py
from django.conf.urls import url

from cta.representante.views import cadastro_representante, apagar_representante, editar_representante


urlpatterns = [
    url(r'^cadastro-representante/$', cadastro_representante, name='representante'),
    url(r'^deletar-representante/(?P<id>\d+)/$', apagar_representante, name='apagarrepresentante'),
    url(r'^editar-representante/(?P<id>\d+)/$', editar_representante, name='editarrepresentante'),
]

cta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cta.core import urls as core_urls
from cta.agendamento import urls as agendamento_urls
from cta.atendimento import urls as atendimento_urls
from cta.fornecedor import urls as fornecedor_urls
from cta.objetivovisita import urls as objetivovisita_urls
from cta.representante import urls as representante_urls

from django.conf import settings

urlpatterns = [
	url(r'', include(core_urls, namespace='core')),
	url(r'', include(agendamento_urls, namespace='agendamento')),
	url(r'', include(atendimento_urls, namespace='atendimento')),
	url(r'', include(fornecedor_urls, namespace='fornecedor')),
	url(r'', include(objetivovisita_urls, namespace='objetivovisita')),
    url(r'', include(representante_urls, namespace='representante')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),    
]

cta/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	telefone = models.CharField(u'Celular', max_length=14, help_text='(99)99999-9999')
	foto = models.ImageField(upload_to="media/profile", blank=True)
	data_cadastro = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.first_name

cta/core/forms.py
from django import forms
from django.contrib.auth.models import User

from cta.core.models import UserProfile

class UserForm(forms.ModelForm):
	#first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		exclude = ('user', 'data_cadastro')

cta/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError

from .forms import UserForm, UserProfileForm
from cta.agendamento.models import Agendamento
from cta.atendimento.models import Atendimento

from cta.fornecedor.models import Fornecedor
from cta.representante.models import Representante
from cta.objetivovisita.models import Objetivovisita

# Create your views here.

from django.contrib.auth.decorators import login_required

def home(request):
	return render(request, 'base.html')

def cadastro_usuario(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user

			if 'foto' in request.FILES:
				profile.foto = request.FILES['foto']

			profile.save()
			return redirect('core:cadastrousuario') #core:usuariosucesso
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'core/cadastro_usuario.html',\
		{'user_form': user_form, 'profile_form': profile_form})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return redirect('core:home') #HttpResponse("Login feito com sucesso.")
			else:				
				mensg = "Sua conta esta desativada."
				return render(request,'core/form_login.html', {'mensg': mensg}) #HttpResponse("Sua conta esta desativada.")
		else:
			mensg = "Usuario ou senha invalido."
			return render(request,'core/form_login.html', {'mensg': mensg}) #HttpResponse("Usuario ou senha invalido.")
	return render(request, 'core/form_login.html')

def sucesso_usuario(request):
	return render(request, 'base.html') #core/sucesso_usuario.html

def user_logout(request):
    logout(request)
    return redirect('core:userlogin')

@login_required(login_url = 'core:userlogin')
def consulta_agendamento(request):
	agendamentos = Agendamento.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_agendamento.html', {'agendamentos': agendamentos})

@login_required(login_url = 'core:userlogin')
def consulta_atendimento(request):
	atendimentos = Atendimento.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_atendimento.html', {'atendimentos': atendimentos})

@login_required(login_url = 'core:userlogin')
def consulta_fornecedor(request):
	fornecedores = Fornecedor.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_fornecedor.html', {'fornecedores': fornecedores})

@login_required(login_url = 'core:userlogin')
def consulta_representante(request):
	representantes = Representante.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_representante.html', {'representantes': representantes})

@login_required(login_url = 'core:userlogin')
def consulta_objetivovisita(request):
	objetivovisitas = Objetivovisita.objects.all() # [:15] --> numero de registro a ser visualizado, objects e igual a select * from tabela
	return render(request, 'core/consulta_objetivovisita.html', {'objetivovisitas': objetivovisitas})

def email_contato(request):
	if request.method == 'POST':
		subject = request.POST.get('subject')
		message = request.POST.get('inputmessage')
		from_email = "flavioleny@gmail.com"
		for_email  = request.POST.get('inputemail')

		if subject and message and for_email:
			send_mail(subject, message, from_email, [for_email], fail_silently=True)

			mensg = "E-mail enviado com Sucesso..."
			return render(request,'core/contato.html', {'mensg': mensg})
		else:
			mensg = "Todos os campos são Obrigatorios."
			return render(request,'core/contato.html', {'mensg': mensg})
	else:
		return render(request, 'core/contato.html')

cta/core/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>{% block titulo %}CTA - Controle de Atendimento{% endblock titulo %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">	
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-datepicker.min.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/dataTables.bootstrap.min.css" %}">

	<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
	<script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
	<script type="text/javascript" src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/bootstrap-datepicker.pt-BR.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/rainbows.js" %}"></script>
	<script type="text/javascript" src="{% static "js/jquery.dataTables.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/dataTables.bootstrap.min.js" %}"></script>
</head>
<body>
	<nav class="navbar navbar-inverse"> <!--  navbar-fixed-top -->
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'core:contato' %}">CTA</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="{% url 'core:home' %}">Home<span class="sr-only">(current)</span></a></li>
	        <li><a href="{% url 'agendamento:agendamento' %}">Agendamento</a></li>
	        <li><a href="{% url 'atendimento:atendimento' %}">Atendimento</a></li>

			<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastros <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="{% url 'fornecedor:fornecedor' %}">Fornecedores</a></li>
	            <li><a href="{% url 'representante:representante' %}">Representantes</a></li>
	            <li><a href="{% url 'objetivovisita:objetivovisita' %}">Objetivo de Visitas</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="{% url 'core:cadastrousuario' %}">Usuarios</a></li>
	          </ul>
	        </li>

			<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Consultas<span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="{% url 'core:consultaagendamento' %}">Agendamento</a></li>
	            <li><a href="{% url 'core:consultaatendimento' %}">Atendimento</a></li>
	            <li role="separator" class="divider"></li>	            
	            <li><a href="{% url 'core:consultafornecedor' %}">Fornecedor</a></li>
	            <li><a href="{% url 'core:consultarepresentante' %}">Representante</a></li>
	            <li><a href="{% url 'core:consultaobjetivovisita' %}">Objetivo Visita</a></li>
	          </ul>
	        </li>
	        <li><a href="{% url 'core:userlogout' %}">Logout</a></li>
	      </ul>
	      <form class="navbar-form navbar-right" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Buscar no Site">
	        </div>
	        <button type="submit" class="btn btn-default">Buscar</button>
	      </form>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<div class="container">
	<div class="row">
		{%  block row %}		
		{% endblock row %}
	</div>
	
</div>
<script type="text/javascript">
	$('.dp3').datepicker({
		format: "dd/mm/yyyy",
    	language: "pt-BR"
	});
	
	$(document).ready(function() {
	    $('#example').DataTable();
	} );

	jQuery(function($){
	       $("#campoHora").mask("99:99:99");
	       $("#campoTelefone").mask("(999) 999-9999");
	       $("#campoSenha").mask("***-****");
	});
</script>
</body>
</html>

cta/core/templates/base_login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>{% block titulo %}CTA - Controle de Atendimento{% endblock titulo %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
	<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
	<script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
	<script type="text/javascript" src="{% static "js/rainbows.js" %}"></script>
</head>
<body>

	<div class="container">
		<div class="row">
			{%  block row %}		
			{% endblock row %}
		</div>
		
	</div>

	<script>
		$(document).ready(function(){
	 
		$("#submit1").hover(
		function() {
		$(this).animate({"opacity": "0"}, "slow");
		},
		function() {
		$(this).animate({"opacity": "1"}, "slow");
		});
	 	});
	</script>

</body>
</html>