cta/atendimento/urls.py
from django.conf.urls import url

from cta.atendimento.views import form_atendimento, apagar_atendimento, editar_atendimento


urlpatterns = [
    url(r'^formulario-atendimento/$', form_atendimento, name='atendimento'),
    url(r'^deletar-atendimento/(?P<id>\d+)/$', apagar_atendimento, name='apagaratendimento'),
    url(r'^editar-atendimento/(?P<id>\d+)/$', editar_atendimento, name='editaratendimento'),    
]

cta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cta.core import urls as core_urls
from cta.agendamento import urls as agendamento_urls
from cta.atendimento import urls as atendimento_urls
from cta.fornecedor import urls as fornecedor_urls
from cta.objetivovisita import urls as objetivovisita_urls
from cta.representante import urls as representante_urls

from django.conf import settings

urlpatterns = [
	url(r'', include(core_urls, namespace='core')),
	url(r'', include(agendamento_urls, namespace='agendamento')),
	url(r'', include(atendimento_urls, namespace='atendimento')),
	url(r'', include(fornecedor_urls, namespace='fornecedor')),
	url(r'', include(objetivovisita_urls, namespace='objetivovisita')),
    url(r'', include(representante_urls, namespace='representante')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),    
]

cta/atendimento/models.py
from django.db import models

# Create your models here.

class Atendimento(models.Model):
	choices_status=(('E','Em Atendimento'),('F','Finalizado'))
	id = models.AutoField(primary_key=True)
	atendente = models.CharField(max_length=20)
	dataatendimento= models.DateTimeField(auto_now_add=True)
	horainicial = models.DateTimeField(auto_now_add=True)
	horafinal = models.DateTimeField(auto_now_add=True)
	representante = models.CharField(max_length=50)
	objetivoatendimento = models.CharField(max_length=20)
	status = models.CharField(u'Status',max_length=1,choices=choices_status) #(Em Atendimento e Finalizado);
	conteudoatendimento = models.TextField(max_length=200)
	observacao = models.CharField(max_length=100)

	def __str__(self):
		return self.atendente

	class Meta:
		verbose_name='Atendimento'
		verbose_name_plural='Atendimento'

cta/atendimento/forms.py
from django import forms

from cta.atendimento.models import Atendimento

class AtendimentoForm(forms.ModelForm):
	class Meta:
		model = Atendimento
		fields = ('atendente','representante', 'objetivoatendimento', 'status', 'conteudoatendimento','observacao')

cta/atendimento/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse

from cta.atendimento.forms import AtendimentoForm
from cta.atendimento.models import Atendimento

# Create your views here.
from django.contrib.auth.decorators import login_required

@login_required(login_url = 'core:userlogin')
def form_atendimento(request):
	newcadastro = 'S'
	if request.method == 'POST':
		atendimento_form = AtendimentoForm(request.POST, request.FILES)
		if atendimento_form.is_valid():
			atendimento_form.save()
			atendimento_form = AtendimentoForm()
			return render(request, 'form_atendimento.html', {'atendimento_form': atendimento_form, 'newcadastro': newcadastro})			
			#return redirect('/')
	else:
		atendimento_form = AtendimentoForm()

	return render(request, 'form_atendimento.html', {'atendimento_form': atendimento_form, 'newcadastro': newcadastro})

def apagar_atendimento(request, id):
	atendimentos = Atendimento.objects.get(id=id).delete()
	return redirect(reverse('core:consultaatendimento'))	

def editar_atendimento(request,id):
	atendimentos = Atendimento.objects.get(id=id)
	newcadastro = 'N'
	if request.method == 'POST':
		atendimento_form = AtendimentoForm(request.POST, instance=atendimentos)
		if atendimento_form.is_valid:
			atendimento_form.save()
			return redirect(reverse('core:consultaatendimento'))
		else:
			print(atendimento_form.errors)
	else:
		atendimento_form = AtendimentoForm(instance=atendimentos)
	
	return render(request, 'form_atendimento.html',{'atendimento_form':atendimento_form, 'newcadastro': newcadastro})

cta/atendimento/templates/form_atendimento.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}
Atendimento | {{ block.super }}
{% endblock titulo %}

{% block row %}

<div class="col-md-8">
	<div class="well bs-component">
		{% if menssagem %}
			{{ menssagem }}
		{% endif %}
		<form class="form-horizontal" action="" method="post" accept-charset="utf-8" enctype="multipart/data-form">
		  <fieldset>
	      	<legend>
		    	{% if newcadastro == 'S' %}
		    		Cadastro de Atendimento
				{% else %}      		
					Editar Atendimento
	      		{% endif %}	 

	      	</legend>	
			{% csrf_token %}
			<div class="form-group">
				<label for="id_atendente" class="col-lg-2 control-label">Atendente</label>
				<div class="col-lg-10">
					{{ atendimento_form.atendente|add_class:"form-control" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_representante" class="col-lg-2 control-label">Representante</label>
				<div class="col-lg-10">
					{{ atendimento_form.representante|add_class:"form-control" }}
				</div>
			</div>		
			<div class="form-group">
				<label for="id_objetivoatendimento" class="col-lg-2 control-label">Objetivo</label>
				<div class="col-lg-10">			
					{{ atendimento_form.objetivoatendimento|add_class:"form-control" }}
				</div>
			</div>		
			<div class="form-group">
				<label for="id_status" class="col-lg-2 control-label">Status</label>
				<div class="col-lg-10">				
					{{ atendimento_form.status|add_class:"form-control" }}
				</div>
			</div>
			<div class="form-group">
				<label for="id_conteudoatendimento" class="col-lg-2 control-label">Conteudo</label>
				<div class="col-lg-10">				
					{{ atendimento_form.conteudoatendimento|add_class:"form-control" }}
				</div>
			</div>		
			<div class="form-group">
				<label for="id_observacao" class="col-lg-2 control-label">Observação</label>
				<div class="col-lg-10">				
					{{ atendimento_form.observacao|add_class:"form-control" }}
				</div>
			</div>
			<button type="submit" class="btn btn-primary">Salvar</button>
			</fieldset>
		</form>
	</div>
</div>
{% endblock row %}